dir: ""
filename: "moq_{{.InterfaceName}}_test.go"
structname: "Moq{{.InterfaceName}}"
template: "matryer"
template-data:
  with-resets: true
packages:
  "github.com/dsh2dsh/expx-cache-redis":
    interfaces:
      "Cmdable":
  "github.com/redis/go-redis/v9":
    interfaces:
      "Pipeliner":
